name: Python Tests

on:
  push:
    branches: [ main, task-1 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget
        # Install TA-Lib
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/usr
        make
        sudo make install
        cd ..
        
    - name: Install basic Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pytest pytest-cov
        
    - name: Install core dependencies first
      run: |
        # Install numpy and pandas first
        pip install numpy==1.24.4 pandas==2.0.2
        
    - name: Install visualization dependencies
      run: |
        # Install matplotlib and related packages
        pip install matplotlib==3.7.5 seaborn==0.13.0
        
    - name: Install scientific packages
      run: |
        pip install scipy==1.10.1 scikit-learn==1.3.2
        
    - name: Install NLP packages
      run: |
        pip install nltk==3.8.1 textblob==0.17.1 vaderSentiment==3.3.2
        
    - name: Install financial packages
      timeout-minutes: 10
      run: |
        # Install financial packages with timeout
        pip install ta-lib==0.4.28 --no-build-isolation
        pip install yfinance==0.2.33
        # Install the rest of dependencies
        pip install jupyter==1.0.0 notebook==7.0.6 pytest==7.4.3
        pip install python-dateutil==2.9.0.post0 pytz==2025.2 six==1.17.0 tzdata==2025.2
        pip install tqdm==4.66.1 plotly==5.18.0
        pip install black==23.11.0 flake8==6.1.0 python-dotenv==1.0.0
    - name: Test with pytest
      run: |
        pytest tests/ --cov=src/ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
