name: Python Tests

on:
  push:
    branches: [ main, task-1 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    # No Miniconda needed with this approach
    - name: Upgrade pip, setuptools, and wheel for Python 3.8
      if: matrix.python-version == '3.8'
      run: |
        python -m pip install --upgrade pip==23.3.2
        python -m pip install --upgrade setuptools wheel
    - name: Upgrade pip, setuptools, and wheel for Python 3.9
      if: matrix.python-version == '3.9'
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install setuptools==68.2.2

    - name: Upgrade pip, setuptools, and wheel for Python 3.10
      if: matrix.python-version == '3.10'
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install setuptools==68.2.2

    - name: Install TA-Lib C library
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential wget
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/usr
        make V=1
        sudo make install
        sudo ldconfig
        cd ..
    - name: Verify TA-Lib C library installation
      run: |
        echo "Verifying TA-Lib C library installation..."
        if [ -f /usr/include/ta-lib/ta_libc.h ]; then echo "Found /usr/include/ta-lib/ta_libc.h"; else echo "ERROR: /usr/include/ta-lib/ta_libc.h not found"; exit 1; fi
        if [ -f /usr/lib/libta_lib.so ]; then echo "Found /usr/lib/libta_lib.so"; else echo "ERROR: /usr/lib/libta_lib.so not found"; exit 1; fi
        if command -v ta-lib-config &> /dev/null; then
            echo "ta-lib-config found in PATH. CFLAGS: $(ta-lib-config --cflags), LIBS: $(ta-lib-config --libs)"
        elif [ -f /usr/bin/ta-lib-config ]; then
            echo "ta-lib-config found at /usr/bin/ta-lib-config. CFLAGS: $(/usr/bin/ta-lib-config --cflags), LIBS: $(/usr/bin/ta-lib-config --libs)"
        else
            echo "Warning: ta-lib-config not found."
        fi
        echo "Listing /usr/lib for libta_lib*"
        ls -l /usr/lib/libta_lib*
        echo "Listing /usr/include/ta-lib for ta_*.h"
        ls -l /usr/include/ta-lib/ta_*.h

    - name: Install dependencies
      env:
        TA_INCLUDE_PATH: /usr/include
        TA_LIBRARY_PATH: /usr/lib
      run: |
        # Install pytest first
        pip install pytest pytest-cov
        
        # Install specific versions of numpy and other build dependencies
        pip install numpy==1.24.4 Cython
        
        # Install ta-lib from source directly
        git clone https://github.com/mrjbq7/ta-lib.git ta-lib-python
        cd ta-lib-python
        git checkout tags/TA_Lib-0.4.24
        python setup.py build
        python setup.py install
        cd ..
        
        # Install the rest of the requirements, excluding ta-lib which we already installed
        if [ -f requirements.txt ]; then
          grep -v "^ta-lib==\|^numpy==" requirements.txt > filtered_requirements.txt
          echo "Filtered requirements:"
          cat filtered_requirements.txt
          pip install -r filtered_requirements.txt
        fi
    - name: Test with pytest
      run: |
        # Check if tests directory exists, and run tests if it does
        if [ -d "tests" ]; then
          pytest tests/ --cov=src/ --cov-report=xml
        elif [ -d "test" ]; then
          pytest test/ --cov=src/ --cov-report=xml
        else
          echo "No tests directory found. Skipping tests."
          # Create an empty coverage report for Codecov
          echo '<?xml version="1.0" encoding="UTF-8"?><coverage></coverage>' > coverage.xml
        fi
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
